### ISSUE TITLE
Improve the overall quality of the website

### ISSUE THREAD

**Issue by adithyanandakumar** [adithyanandakumar/me#2]
You can  - 

- [ ] add more animations
- [ ] replace social media icons
- [ ] improve responsiveness
- [ ] add interactions
- [ ] add widgets etc.

You need not stick to the above tasks, you can come up with your own to enhance the website

**Comment by Himanshu664** [comment]
@adithyanandakumar I am facing some diffiulty in Issue 1 so I unassigned myself please assign me this this I want to add Social media icons .
